version: "3"
services:
  app:
    build: .
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - postgres
  postgres:
    image: postgres:14
    volumes:
      - database:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file:
      - .env
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U test -d vws_postgres14" ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 4G
  postgres_test:
    image: postgres:14
    volumes:
      - database_test:/var/lib/postgresql/testdata
    ports:
      - "5433:5432"
    env_file:
      - test.env
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U test -d vws_postgres14_test" ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 4G
volumes:
  database:
  database_test: