spring:
  datasource:
    url: 'jdbc:postgresql://${DB_LOCATION}:5432/vws_postgres14?useUnicode=true&serverTimezone=CET'
    username: test
    password: test
    driver-class-name: org.postgresql.Driver
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
  # Show or not log for each sql query
  jpa:
    show-sql: true
  # Hibernate ddl auto (create, create-drop, update): with "update" the database
  # schema will be automatically updated accordingly to java entities found in
  # the project
    hibernate:
      ddl-auto: update
      #use-new-id-generator-mappings: true
  # Allows Hibernate to generate SQL optimized for a particular DBMS
    database: postgresql
    #database-platform: 'org.hibernate.dialect.PostgreSQL95Dialect'
  #Gmail properties
  mail:
    host: smtp.gmail.com
    port: 587
    username: passant.dlm@gmail.com
    password: hazxergxtbhftgdc
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

words:
  defaultWordCount: 50
  wordsApiKey: 55k0ykdy6pe8fmu69pwjk94es02i9085k3h1hn11ku56c4qep
  translationApiKey: '6c7b1dbe-c308-3d45-dd62-81fe723d988d:fx'

logging:
  config: 'classpath:log4j2.xml'